import type { Metadata } from "next";
import { Inter, Kantumruy_Pro } from "next/font/google";
// @ts-expect-error: remove error on global css
import "./globals.css";
import Navbar from "@/components/navbar/Navbar";
import Footer from "@/components/footer/Footer";
import { Suspense } from "react";
import Loading from "./loading";

const kantumruyPro = Kantumruy_Pro({
  variable: "--font-kh",
  subsets: ["latin"],
});

const inter = Inter({
  variable: "--font-en",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.6.0/css/all.min.css"
        />
      <body
        className={`${kantumruyPro.variable} ${inter.variable} antialiased`}
      >
        <div className="font-en">
          <Navbar />
          <Suspense fallback={<Loading />}>{children}</Suspense>
          <Footer />
        </div>
      </body>
    </html>
  );
}
